### PR TITLE
Fixes issue with pricing coupon and plan mismatches

### LINKED ISSUE #175: Validating plan-restricted coupons
When creating a code that is restricted to certain plans, Recurly.js doesn't appear to be updating the totals correctly when the coupon is set and then the plan is changed. The totals update, but the coupon is applied regardless of the plan restriction.

### Steps to reproduce:

1. Select the plan (we are using radio inputs).
2. Enter the coupon code that works with that plan.
3. Change the plan.

At this point the coupon's discount is applied even though it is restricted to only one plan. I can change the plan to any of our listed subscription plans and it still calculates the discount.

### Inverse issue:

1. Select the plan (one that isn't allowed on the coupon)
2. Enter the coupon code.
3. Change the plan to the one that is allowed on that coupon.

The discount remains at $0 even when the correct plan is chosen. No matter which plan is chosen, the discount remains at $0.

### Coupon settings

Just in case it matters, the coupon we setup has the following options:

1. 25% discount
2. Single use
3. Unlimited redemptions
4. Never expires
5. Only affects one plan (which is annual)

Is this on anyone's radar? Or is there a way to work around it?

### PR DESCRIPTION
**Pull request by chrissrogers**
- Calls to pricing.coupon will no longer abort if the coupon code hasn't changed. This accomodates plan changes that may nullify a coupon that may wok on other plans
- Corrects not-found error code check in pricing.coupon
- pricing.plan calls will now make pricing.coupon calls if a coupon is set on the instance
- Fixes #175

### CODE REVIEW

File: lib/recurly/pricing/attach.js [hunk 1]
```diff
@@ -53,11 +53,11 @@ exports.attach = function (el) {
       pricing = pricing.currency(dom.value(elems.currency));
     }
 
-    if (target('addon') && elems.addon) {
+    if (elems.addon && target('addon')) {
       addons();
     }
 
-    if (target('coupon') && elems.coupon) {
+    if (elems.coupon && (target('coupon') || target('plan'))) {
```
Comment (chrissrogers) [inline lib/recurly/pricing/attach.js]: I switched these around since the `target` method calls are a bit more expensive. Should speed things up marginally for forms not using addons or coupons.

File: lib/recurly/pricing/index.js [hunk 2]
```diff
@@ -243,14 +252,18 @@ Pricing.prototype.coupon = function (couponCode, done) {
...
+    if (!couponCode) {
+      debug('unset.coupon');
+      delete self.items.coupon;
+      return resolve();
     }
-    if (!couponCode) return resolve();
 
     self.recurly.coupon({ plan: self.items.plan.code, coupon: couponCode }, function (err, coupon) {
-      if (err && err.code !== 'not_found') return reject(err);
+      if (err && err.code !== 'not-found') return reject(err);
```
Comment (chrissrogers) [inline lib/recurly/pricing/index.js]: I'd like to follow up on this PR with some reconsideration of how we handle not-found coupons. Right now we ignore the error completely, but I think we should probably emit an event that merchants can listen to. See #176

File: lib/recurly/pricing/index.js [hunk 3]
```diff
@@ -243,14 +252,18 @@ Pricing.prototype.coupon = function (couponCode, done) {
...
-      if (coupon.code === couponCode) return resolve(coupon);
-      else self.remove({ coupon: coupon.code });
+    if (coupon) self.remove({ coupon: coupon.code });
+
+    // TODO: Should this emit an 'unset' event?
+    // Need to consider other objects as well
+    if (!couponCode) {
+      debug('unset.coupon');
+      delete self.items.coupon;
+      return resolve();
```
Comment (chrissrogers) [inline lib/recurly/pricing/index.js]: This adds a new class of events: `unset` -- I'd like to follow this PR with one adding `unset` events to the remaining objects.

File: lib/recurly/pricing/index.js [hunk 4]
```diff
@@ -243,14 +252,18 @@ Pricing.prototype.coupon = function (couponCode, done) {
 
   return new PricingPromise(function (resolve, reject) {
     if (!self.items.plan) return reject(errors('missing-plan'));
-    if (coupon) {
-      if (coupon.code === couponCode) return resolve(coupon);
-      else self.remove({ coupon: coupon.code });
+    if (coupon) self.remove({ coupon: coupon.code });
```
Comment (chrissrogers) [inline lib/recurly/pricing/index.js]: This ensures we always process coupon set calls, since plans may have changed between calls. I don't think we should be tracking plan change histories in the coupon method.

File: lib/recurly/pricing/index.js [hunk 5]
```diff
@@ -170,9 +170,18 @@ Pricing.prototype.plan = function (planCode, meta, done) {
...
 
-      debug('set.plan');
-      self.emit('set.plan', plan);
-      resolve(plan);
+      // If we have a coupon, it must be reapplied
+      if (self.items.coupon) {
+        self.coupon(self.items.coupon.code).then(finish, finish);
+      } else {
+        finish();
+      }
```
Comment (chrissrogers) [inline lib/recurly/pricing/index.js]: Thus when we change plans, we reapply the potentially plan-dependent coupon.

We don't expose in the API which plans a coupon applies to since that may be sensitive information a merchant doesn't wish to expose publicly. The result is more API calls.
